/**
 * Environment File Writer
 *
 * Securely writes API keys to ~/.devfolio/.env
 */

import { homedir } from 'os';
import { join } from 'path';
import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from 'fs';

const ENV_DIR = join(homedir(), '.devfolio');
const ENV_PATH = join(ENV_DIR, '.env');

/**
 * Ensure the devfolio directory exists
 */
function ensureDir(): void {
  if (!existsSync(ENV_DIR)) {
    mkdirSync(ENV_DIR, { recursive: true, mode: 0o700 });
  }
}

/**
 * Read existing .env file as key-value pairs
 */
function readEnv(): Record<string, string> {
  if (!existsSync(ENV_PATH)) {
    return {};
  }

  const content = readFileSync(ENV_PATH, 'utf-8');
  const env: Record<string, string> = {};

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const eqIndex = trimmed.indexOf('=');
    if (eqIndex > 0) {
      const key = trimmed.slice(0, eqIndex).trim();
      let value = trimmed.slice(eqIndex + 1).trim();
      // Remove quotes if present
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      env[key] = value;
    }
  }

  return env;
}

/**
 * Write environment variables to .env file
 */
function writeEnv(env: Record<string, string>): void {
  ensureDir();

  const lines = [
    '# DevFolio Configuration',
    '# Generated by setup wizard',
    '#',
    '# Get API keys at:',
    '#   Groq: https://console.groq.com',
    '#   OpenAI: https://platform.openai.com',
    '#   Anthropic: https://console.anthropic.com',
    '',
  ];

  for (const [key, value] of Object.entries(env)) {
    if (value) {
      lines.push(`${key}=${value}`);
    }
  }

  writeFileSync(ENV_PATH, lines.join('\n') + '\n', { mode: 0o600 });
}

/**
 * Set an API key in the .env file
 */
export function setEnvKey(key: string, value: string): void {
  const env = readEnv();
  env[key] = value;
  writeEnv(env);
}

/**
 * Remove an API key from the .env file
 */
export function removeEnvKey(key: string): void {
  const env = readEnv();
  delete env[key];
  writeEnv(env);
}

/**
 * Get the .env file path
 */
export function getEnvPath(): string {
  return ENV_PATH;
}

/**
 * Check if .env file exists
 */
export function envExists(): boolean {
  return existsSync(ENV_PATH);
}

/**
 * Check if any API key is configured
 */
export function hasApiKey(): boolean {
  const env = readEnv();
  return !!(env.GROQ_API_KEY || env.OPENAI_API_KEY || env.ANTHROPIC_API_KEY);
}

/**
 * Get all configured providers
 */
export function getConfiguredProviders(): string[] {
  const env = readEnv();
  const providers: string[] = [];

  if (env.GROQ_API_KEY) providers.push('groq');
  if (env.OPENAI_API_KEY) providers.push('openai');
  if (env.ANTHROPIC_API_KEY) providers.push('anthropic');

  return providers;
}
